[book]
authors = []
language = "zh"
description = "robonix 手册"
src = "src"
title = "robonix 手册"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = ["theme/wide.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "auto"
git-repository-url = "https://github.com/syswonder/robonix"
mathjax-support = true

[output.html.fold]
enable = true
level = 1
