#!/usr/bin/env python3
"""Check every internal link and fragment in the generated Docusaurus site."""

from __future__ import annotations

import argparse
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urljoin, urlsplit


IGNORED_SCHEMES = {"data", "javascript", "mailto", "tel"}
GENERATED_API_PREFIX = "/api/"


class PageParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.hrefs: list[str] = []
        self.anchors: set[str] = set()

    def handle_starttag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        values = dict(attrs)
        anchor = values.get("id")
        if anchor:
            self.anchors.add(anchor)
        if tag == "a" and values.get("href"):
            self.hrefs.append(values["href"] or "")


def parse_page(path: Path) -> PageParser:
    parser = PageParser()
    parser.feed(path.read_text(encoding="utf-8"))
    return parser


def page_route(page: Path, build: Path) -> str:
    relative = page.relative_to(build)
    if relative.name == "index.html":
        parent = relative.parent.as_posix()
        return "/" if parent == "." else f"/{parent}/"
    return f"/{relative.with_suffix('').as_posix()}"


def output_for_path(path: str, build: Path) -> Path | None:
    relative = unquote(path).lstrip("/")
    if not relative:
        return build / "index.html"

    direct = build / relative
    candidates = [direct]
    if path.endswith("/"):
        candidates.insert(0, direct / "index.html")
    else:
        # Routes generated by Sphinx commonly contain dots in the page name
        # (for example ``robonix_api.atlas``).  A dot is not proof that the
        # URL already has a file extension, so append ``.html`` instead of
        # replacing the final dotted segment.
        candidates.extend([Path(f"{direct}.html"), direct / "index.html"])

    return next((candidate for candidate in candidates if candidate.is_file()), None)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("build", type=Path)
    args = parser.parse_args()

    pages = sorted(args.build.rglob("*.html"))
    generated_pages_skipped = sum(
        page_route(page, args.build).startswith(GENERATED_API_PREFIX)
        for page in pages
    )
    # Sphinx and rustdoc own their generated trees and may intentionally link
    # to dependency documentation omitted by ``cargo doc --no-deps``.  The
    # Book checks that handbook links resolve to real API files, while each
    # generator is responsible for navigation inside its own output.
    parsed = {
        page: parse_page(page)
        for page in pages
        if not page_route(page, args.build).startswith(GENERATED_API_PREFIX)
    }
    failures: list[str] = []
    checked = 0
    generated_fragments_skipped = 0

    for source, document in parsed.items():
        source_route = page_route(source, args.build)
        for href in document.hrefs:
            target = urlsplit(href)
            if target.scheme in IGNORED_SCHEMES or target.netloc:
                continue

            resolved = urlsplit(urljoin(source_route, href))
            output = output_for_path(resolved.path, args.build)
            checked += 1
            if output is None:
                failures.append(f"{source_route}: missing target {href}")
                continue

            if resolved.fragment and output.suffix == ".html":
                # rustdoc source-line anchors and Furo navigation anchors are
                # materialized or normalized by their own JavaScript at page
                # load time. File targets remain checked above, while static
                # fragment validation is reserved for the Docusaurus pages we
                # generate and control.
                output_route = page_route(output, args.build)
                if output_route.startswith(GENERATED_API_PREFIX):
                    generated_fragments_skipped += 1
                    continue
                target_page = parsed.get(output)
                if target_page is None:
                    target_page = parse_page(output)
                    parsed[output] = target_page
                fragment = unquote(resolved.fragment)
                if fragment not in target_page.anchors:
                    failures.append(
                        f"{source_route}: missing fragment #{fragment} in {href}"
                    )

    if failures:
        for failure in failures:
            print(failure)
        raise SystemExit(1)
    print(
        f"built link check: {checked} internal targets available; "
        f"skipped {generated_pages_skipped} generated API pages and "
        f"{generated_fragments_skipped} generated API fragments"
    )


if __name__ == "__main__":
    main()
